[workspace]
resolver = "2"
members = ["packages/*"]

[workspace.package]
edition = "2021"
rust-version = "1.91.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
pest = "2.8.4"
pest_derive = "2.8.4"
thiserror = "2.0.17"
