[package]
name = "fabulist_lang"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
pest.workspace = true
thiserror.workspace = true
pest_derive = { workspace = true, features = ["grammar-extras"] }

fabulist_core = { path = "../fabulist_core" }
fabulist_derive = { path = "../fabulist_derive" }
