[package]
name = "fabc_analyzer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fabc_error = { path = "../fabc_error" }
fabc_parser = { path = "../fabc_parser" }
