[package]
name = "fabc_ir_generator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fabc_parser = { path = "../fabc_parser" }
fabc_analyzer = { path = "../fabc_analyzer" }
fabc_error = { path = "../fabc_error" }
