[package]
name = "fabc_error"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anstyle = "1.0.13"
fabc_lexer = { path = "../fabc_lexer" }
